#!/bin/bash

if [[ "$1" != "" ]]; then
    PORT="$1"
else
    echo "Enter port number to check:"
    read PORT
fi

PORT_OUTPUT=$(sudo lsof -i :$PORT -P -n | grep LISTEN)

if  [[  $PORT_OUTPUT  ]];  then
    echo ${PORT_OUTPUT}
else
    echo "Port not in use!"
fi